// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wtvhogdazobwzkaavxpp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0dmhvZ2Rhem9id3prYWF2eHBwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3NzE1NDYsImV4cCI6MjA1NjM0NzU0Nn0.YQAsUDBRekdwZT_a4goeMw0WxdV4wIme2D4-wQ8MkiE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);